---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: static-website
spec:
  rules:
  - host: demoniacdeath.me
    http:
      paths:
      - backend:
          serviceName: static-website
          servicePort: 80
  tls:
  - hosts:
    - demoniacdeath.me
    secretName: static-website-cert
